// SPDX-License-Identifier: GPL-2.0-or-later
/*
 *
 *
 * Copyright (C) 2025 Daniel Wegkamp
 */

 // acces port types according to IHI0031G_debug_interface_v5_2_architecture_specification

[0x008] = "Cortex-M0+ SCS",    // System Control Space
[0x00A] = "Cortex-M0+ DWT",     // Data Watchpoint Unit
[0x00B] = "Cortex-M0+ BPU",    // BreakPoint Unit
[0x4c0] = "Cortex-M0+ ROM",
[0x417] = "STM32L0x3 maybe?"
/* EOF */
