 // SPDX-License-Identifier: GPL-2.0-or-later
/*
 *
 *
 * Copyright (C) 2025 Daniel Wegkamp
 */
[0x003] = "Cortex M4 FPB",
[0x008] = "Cortex-M0+ SCS",         // System Control Space
[0x00A] = "Cortex-M0+ DWT",         // Data Watchpoint Unit
[0x00B] = "Cortex-M0+ BPU",         // BreakPoint Unit
[0x00C] = "Cortex-M4 SCS",
[0x4c0] = "Cortex-M0+ ROM",
[0x411] = "STM32F2xxxx",            // from cd00167594-stm32-microcontroller-system-memory-boot-mode-stmicroelectronics-1.pdf
[0x417] = "STM32L0x3 maybe?",
[0x423] = "STM32F401xB/C",
[0x433] = "STM32F401xD/E",
[0x440] = "STM32F05xxx/F030x8",     //
[0x442] = "STM32F030xC",
[0x446] = "STM32F302xD(E)/303xD(E)/STM32F398xx",
[0x925] = "Cortex-M4 ETM",
[0x9A1] = "Cortex-M3/M4 TPIU"
/* EOF */
