// SPDX-License-Identifier: GPL-2.0-or-later
/*
 *
 *
 * Copyright (C) 2025 Daniel Wegkamp
 */

 // acces port types according to IHI0031G_debug_interface_v5_2_architecture_specification

[0x0] = "JTAG or COM-AP",
[0x1] = "AMBA AHB3 bus",
[0x2] = "AMBA APB2 or APB3 bus",
[0x3] = "reserved",
[0x4] = "AMBA AXI3 or AXI4",
[0x5] = "AMBA AHB5",
[0x6] = "AMBA APB4 or APB5",
[0x7] = "AMBA AXI5",
[0x8] = "AMBA AHB5 w. enh. HPROT",
/* EOF */
