// SPDX-License-Identifier: GPL-2.0-or-later
/*
 *
 *
 * Copyright (C) 2025 Daniel Wegkamp
 */

[0x01] = "ROM Table",         // System Control Space
[0x02] = "SCS",         // Data Watchpoint Unit
[0x03] = "DWT",         // BreakPoint Unit
[0x04] = "BPU",
[0x05] = "FPB",
[0x06] = "ITM",            // from cd00167594-stm32-microcontroller-system-memory-boot-mode-stmicroelectronics-1.pdf
[0x07] = "TPIU",
[0x08] = "ETM",
/* EOF */
